apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-service
spec:
  ports:
    - port: 80
      nodePort: 31000
      targetPort: 80
      protocol: TCP
  selector:
    app: nodejs-app-service
  type: NodePort