replicaCount: 2

image:
  repository: bogdansolga/skyhop-fe
  tag: "0.1"
  pullPolicy: IfNotPresent

service:
  port: 3000

ingress:
  enabled: true
  className: nginx
  host: skyhop.local

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 256Mi
