apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodejs-app-with-secrets
  name: nodejs-app-with-secrets
spec:
  selector:
    matchLabels:
      app: nodejs-app-with-secrets
  template:
    metadata:
      labels:
        app: nodejs-app-with-secrets
    spec:
      containers:
        - name: nodejs-app
          image: bogdansolga/nodejs-app:1.0
          volumeMounts:
          - name: creds-volume
            mountPath: /etc/creds
            readOnly: true
      volumes:
      - name: creds-volume
        secret:
          secretName: db-credentials