apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
type: Opaque
data:
  DATABASE_NAME: ZGF0YWJhc2UtbmFtZQ== #database-name
  DATABASE_PASSWORD: ZGF0YWJhc2UtcGFzc3dvcmQ= #database-password
