apiVersion: batch/v1
kind: CronJob
metadata:
  name: scheduled-pi-computation
spec:
  schedule: "* * * * 1"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: busybox
              image: busybox:1.36.1
              command:
                - /bin/sh
                - -c
                - date; echo Running a scheduled task
          restartPolicy: Never