apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"java-app-in-k8s","namespace":"default"},"spec":{"replicas":2,"selector":{"matchLabels":{"run":"java-app-in-k8s"}},"template":{"metadata":{"labels":{"app":"java-app-in-k8s","run":"java-app-in-k8s"}},"spec":{"containers":[{"image":"bogdansolga/java-app:1.0","name":"java-app"}]}}}}
  creationTimestamp: "2020-03-28T16:46:25Z"
  generation: 4
  name: java-app-in-k8s
  namespace: default
  resourceVersion: "110934"
  selfLink: /apis/apps/v1/namespaces/default/deployments/java-app-in-k8s
  uid: 260012dd-72b9-417f-a520-be62e0d0907f
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: java-app-in-k8s
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-app-in-k8s
        run: java-app-in-k8s
    spec:
      containers:
      - image: bogdansolga/java-app:1.0
        imagePullPolicy: IfNotPresent
        name: java-app
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2020-03-28T16:46:25Z"
    lastUpdateTime: "2020-03-28T17:26:57Z"
    message: ReplicaSet "java-app-in-k8s-6b4db4cc87" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2020-03-28T18:44:29Z"
    lastUpdateTime: "2020-03-28T18:44:29Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 4
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
