apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app-in-k8s
  labels:
    app: java-app-in-k8s
    environment: staging
    pizza: 'with-everything-in-it'
  annotations:
    shortDescription: 'This Deployment is used for the... whatever it is'
spec:
  selector:
    matchLabels:
      app: java-app-in-k8s
  template:
    metadata:
      labels:
        app: java-app-in-k8s
        environment: dev
    spec:
      containers:
        - image: bogdansolga/java-app:1.0
          name: java-app
          ports:
            - containerPort: 8080
          env:
            - name: ENVIRONMENT
              value: dev

  replicas: 3
  revisionHistoryLimit: 1
