apiVersion: v1
kind: Pod
metadata:
  name: front-end
spec:
  containers:
    - name: front-end
      image: nginx:1.26-alpine
      volumeMounts:
        - mountPath: "/var/www/html"
          name: first-persistent-volume

  # can be used by all the containers from that Pod
  volumes:
    - name: first-persistent-volume
      persistentVolumeClaim:
        claimName: first-volume-claim