apiVersion: v1
kind: Pod
metadata:
  name: pod-with-config-map-as-volume
  labels:
    app: container-with-config-map-as-volume
spec:
  containers:
  - name: container-with-config-map-as-volume
    image: bogdansolga/java-app:1.0
    ports:
    - containerPort: 8080
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config/network
  volumes:
  - name: config-volume
    configMap:
      name: conn-config