apiVersion: v1
kind: ReplicationController
metadata:
  name: nodejs-app-with-repl-controller
spec:
  replicas: 2
  selector:
    app: nodejs-app-with-repl-controller
  template:
    metadata:
      labels:
        app: nodejs-app-with-repl-controller
        feat: replication-controller
    spec:
      containers:
      - name: nodejs-app
        image: bogdansolga/nodejs-app:1.0
        ports:
        - name: nodejs-port
          containerPort: 3000