apiVersion: v1
kind: Service
metadata:
  name: nodejs-hello-kubernetes-service
spec:
  ports:
    - port: 80
      target-port: nodejs-hello-kubernetes-node-port
      protocol: TCP
    selector:
      app: nodejs-hello-kubernetes
    type: LoadBalancer