apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: simple-cron-job
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: simple-cron-job
            image: busybox
            args:
            - /bin/sh
            - -c
            - echo Will run every minute
          restartPolicy: OnFailure
